# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["me@jakechampion.name"]
description = "hn"
language = "javascript"
manifest_version = 2
name = "hn"
service_id = "35VfiGSqO4qK9yI0i7ZUyC"

[scripts]
  build = "npm run build"

[local_server]

  [local_server.backends]

    [local_server.backends.hn]
      override_host = "api.hnpwa.com"
      url = "https://api.hnpwa.com"
