name: Deploy Application

concurrency: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Download Yarn and the Fastly CLI and install the project dependencies
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        cli_version: '10.2.0'
    - run: yarn

    - run: fastly compute publish --verbose -i --service-id 35VfiGSqO4qK9yI0i7ZUyC --token ${{ secrets.FASTLY_API_TOKEN }}
