name: Deploy Application

concurrency: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install project dependencies
      run: npm ci

    - name: Deploy to Compute@Edge
      uses: fastly/compute-actions@v1
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}